name: ml_text_extractor_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.20.0
  image_picker: ^0.8.5+3
  google_ml_kit: ^0.12.0
  clipboard: ^0.1.3
  share_plus: ^4.1.0
  contactus: ^1.2.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.5


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

